const days=[
{id:'d1',date:'5 aug',area:'Loch Lomond',route:'Glasgow → Loch Lomond',image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=85',center:[56.06,-4.59],zoom:11,drive:'ca 55 km',time:'ca 1 h 15 min',overnight:'Loch Lomond',focus:'Lugn start',note:'Prioritera Conic Hill när sikten är bra. Luss fungerar fint senare på dagen.'},
{id:'d2',date:'6 aug',area:'Glencoe',route:'Loch Lomond → Glencoe',image:'https://images.unsplash.com/photo-1486299267070-83823f5448dd?auto=format&fit=crop&w=1600&q=85',center:[56.68,-5.05],zoom:11,drive:'ca 105 km',time:'ca 2 h',overnight:'Glencoe',focus:'Vandring',note:'Lost Valley är dagens huvudaktivitet. Three Sisters är ett enkelt stopp före eller efter.'},
{id:'d3',date:'7 aug',area:'Glen Etive',route:'Glencoe → Glen Etive',image:'https://images.unsplash.com/photo-1491555103944-7c647fd857e6?auto=format&fit=crop&w=1600&q=85',center:[56.61,-4.97],zoom:11,drive:'Flexibel',time:'Halvdag',overnight:'Glencoe',focus:'Fotostopp',note:'Vägen in i Glen Etive är smal. Ta god tid och använd mötesplatserna.'},
{id:'d4',date:'8 aug',area:'Skye söder',route:'Glencoe → Isle of Skye',image:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=85',center:[57.25,-6.26],zoom:10,drive:'ca 185 km',time:'ca 3 h 45 min',overnight:'Skye',focus:'Transport + utsikt',note:'Välj Elgol eller Fairy Pools beroende på ankomsttid. Försök inte pressa in båda sent.'},
{id:'d5',date:'9 aug',area:'Skye nord',route:'Portree → Trotternish',image:'https://images.unsplash.com/photo-1506377585622-bedcbb027afc?auto=format&fit=crop&w=1600&q=85',center:[57.55,-6.27],zoom:10,drive:'ca 75 km',time:'Heldag',overnight:'Skye',focus:'Resans stora vandringsdag',note:'Old Man of Storr och Quiraing samma dag kräver tidig start. Fairy Glen är bonus.'},
{id:'d6',date:'10 aug',area:'Skye väster',route:'Portree → Neist Point',image:'https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1600&q=85',center:[57.42,-6.56],zoom:10,drive:'ca 95 km',time:'Flexibel heldag',overnight:'Skye',focus:'Kust & solnedgång',note:'Planera Neist Point sist. Parkeringen blir snabbt full och vägen är smal.'},
{id:'d7',date:'11 aug',area:'Harris',route:'Uig → Tarbert',image:'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1600&q=85',center:[57.90,-6.91],zoom:10,drive:'Färjedag',time:'Beroende på avgång',overnight:'Harris',focus:'Färja + strand',note:'Var i Uig i mycket god tid. Luskentyre blir dagens naturliga höjdpunkt efter ankomst.'},
{id:'d8',date:'12 aug',area:'Harris',route:'Södra Harris → Hushinish',image:'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=85',center:[57.93,-6.95],zoom:10,drive:'ca 90 km',time:'Heldag',overnight:'Harris',focus:'Stränder',note:'Hushinish är en destination i sig. Northton och Scarista passar på vägen söderut.'},
{id:'d9',date:'13 aug',area:'Lewis',route:'Harris → Lewis',image:'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1600&q=85',center:[58.29,-6.55],zoom:9,drive:'ca 165 km',time:'Lång dag',overnight:'Lewis',focus:'Historia',note:'Callanish och Gearrannan är huvudstopp. Butt of Lewis är en bonus om tiden räcker.'},
{id:'d10',date:'14 aug',area:'Pitlochry',route:'Stornoway → Ullapool → Pitlochry',image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=85',center:[56.71,-3.80],zoom:10,drive:'Lång transport',time:'Färja + ca 3 h',overnight:'Pitlochry',focus:'Transportdag',note:'Håll eftermiddagen enkel. Queen’s View är ett bra stopp om tiden räcker.'},
{id:'d11',date:'15 aug',area:'Stirling',route:'Pitlochry → Stirling',image:'https://images.unsplash.com/photo-1577702312706-e23ff063064f?auto=format&fit=crop&w=1600&q=85',center:[56.12,-3.94],zoom:12,drive:'ca 95 km',time:'ca 1 h 25 min',overnight:'Stirling',focus:'Slott & historia',note:'Stirling Castle är dagens prioritet. Curly Coo passar bäst på kvällen.'},
{id:'d12',date:'16 aug',area:'Culross',route:'Stirling → Culross → Falkirk',image:'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1600&q=85',center:[56.04,-3.72],zoom:11,drive:'ca 70 km',time:'Flexibel',overnight:'Stirling',focus:'Småstad & design',note:'Culross är bäst till fots. Avsluta med The Kelpies när ljuset är mjukare.'},
{id:'d13',date:'17 aug',area:'Glasgow',route:'Stirling → Glasgow',image:'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1600&q=85',center:[55.86,-4.25],zoom:11,drive:'ca 45 km',time:'ca 45 min',overnight:'Hemresa',focus:'Återlämning',note:'Lämna ordentlig marginal för städning, tankning och återlämning.'}
];
const places=[
['Glasgow','Glasgow','d13',55.8642,-4.2518,'shopping','Start och avslut med shopping, restauranger och praktisk service.','2–4 tim','Stad','Bra tillgång'],
['Luss','Loch Lomond','d1',56.101,-4.6406,'history','Historisk by med strandpromenad och klassisk Loch Lomond-känsla.','45–75 min','Eftermiddag','Parkera utanför bykärnan'],
['Conic Hill','Loch Lomond','d1',56.0868,-4.5393,'hike','Kortare vandring med stor utdelning och utsikt över sjöns öar.','2–3 tim','Morgon','Offentlig parkering i Balmaha'],
['Loch Lomond Shores','Loch Lomond','d1',56.0036,-4.5906,'shopping','Praktiskt första stopp med café, shopping och service.','45 min','Flexibelt','Stor parkering'],
['Duck Bay Marina','Loch Lomond','d1',56.0132,-4.6068,'food','Middag eller drink vid vattnet.','1–2 tim','Kväll','Enkel parkering'],
['Three Sisters','Glencoe','d2',56.6663,-4.9867,'photo','Dramatisk och lättillgänglig utsikt över Glencoes berg.','20–40 min','Tidig morgon','Begränsad vägparkering'],
['Lost Valley','Glencoe','d2',56.6504,-4.999,'hike','Klassisk vandring in i Coire Gabhail.','3–4 tim','Morgon','Populär parkering, kom tidigt'],
['Clachaig Inn','Glencoe','d2',56.6696,-5.0125,'food','Legendarisk Highland-pub med rustik stämning.','1–3 tim','Kväll','Gästparkering'],
['Glen Etive','Glencoe','d3',56.594,-4.93,'nature','Vild och filmisk dal med vattenfall, berg och spontana stopp.','3–5 tim','Eftermiddag','Mycket smal väg'],
['Glenfinnan Viaduct','Mot Skye','d4',56.8763,-5.4318,'history','Ikonisk järnvägsviadukt och bra stopp på vägen mot Skye.','1–2 tim','Kontrollera tågtid','Betalparkering'],
['Fairy Pools','Skye','d4',57.2504,-6.2563,'nature','Klara pooler nedanför Cuillinbergen.','2–3 tim','Tidig morgon','Stor betalparkering'],
['Elgol','Skye','d4',57.146,-6.1073,'photo','Lugn kustby med magnifik utsikt mot Cuillin.','1–2 tim','Kväll','Smal väg sista sträckan'],
['Old Man of Storr','Skye','d5',57.5073,-6.1741,'hike','En av Skyes mest kända vandringar med dramatiska vyer.','2–3 tim','Soluppgång','Betalparkering, fylls tidigt'],
['Quiraing','Skye','d5',57.6434,-6.2653,'hike','Dramatiskt landskap med kort utsiktspromenad eller längre tur.','2–4 tim','Tidig morgon','Begränsad parkering'],
['Fairy Glen','Skye','d5',57.5838,-6.3262,'quirky','Märkligt miniatyrlandskap med tydlig sagokänsla.','45–75 min','Sen eftermiddag','Betalparkering'],
['Portree','Skye','d5',57.4125,-6.194,'shopping','Färgstark hamn, lokala butiker, restauranger och pubar.','2–3 tim','Lunch/kväll','Flera centrala parkeringar'],
['Neist Point','Skye','d6',57.4234,-6.7886,'photo','Dramatiska klippor och ett av resans bästa solnedgångsstopp.','2–3 tim','Solnedgång','Mycket begränsad parkering'],
['Uig Ferry Terminal','Skye','d7',57.586,-6.358,'ferry','Färja från Uig till Tarbert.','Var i god tid','Enligt bokning','Incheckning krävs'],
['Tarbert','Harris','d7',57.8988,-6.8088,'ferry','Ankomsthamn och central ort på Harris.','30–60 min','Efter ankomst','Service nära hamnen'],
['Harris Distillery','Harris','d7',57.8976,-6.8081,'food','Modern destillerimiljö med lokal design, gin och whisky.','1–2 tim','Boka vid behov','Parkering i Tarbert'],
['Luskentyre Beach','Harris','d7',57.8991,-6.9507,'beach','Vidsträckt vit sand, turkost vatten och berg i bakgrunden.','2–4 tim','Sen eftermiddag','Små parkeringsytor'],
['Hushinish Beach','Harris','d8',57.9981,-7.0883,'beach','Avlägsen strand med dramatisk väg och vacker kust.','3–5 tim','Mitt på dagen','Smal väg, kör lugnt'],
['Northton Saltmarsh','Harris','d8',57.806,-6.971,'nature','Saltängar och tidvattenlandskap på södra Harris.','45–90 min','Lågvatten','Begränsad parkering'],
['Scarista Beach','Harris','d8',57.813,-6.999,'beach','Vild strand med vågor och utsikt mot Harrisbergen.','1–2 tim','Eftermiddag','Parkera hänsynsfullt'],
['Calanais Standing Stones','Lewis','d9',58.1973,-6.745,'history','Förhistorisk stencirkel och en av Hebridernas starkaste kulturupplevelser.','1–2 tim','Kväll','Besöksparkering'],
['Gearrannan Blackhouse Village','Lewis','d9',58.2952,-6.7931,'history','Restaurerad by med traditionella svartstenhus och kustlandskap.','1–2 tim','Eftermiddag','Besöksparkering'],
['Butt of Lewis','Lewis','d9',58.515,-6.261,'nature','Vindpinad nordspets med fyr och Atlantklippor.','1–2 tim','Dagsljus','Öppen parkering'],
['Stornoway','Lewis','d9',58.2093,-6.3865,'shopping','Service, caféer, butiker och färjehamn.','1–2 tim','Före färja','Bra serviceutbud'],
['Ullapool','Fastlandet','d10',57.8954,-5.1613,'ferry','Ankomst från Stornoway och start för färden söderut.','1 tim','Efter ankomst','Service nära hamnen'],
["Queen's View",'Pitlochry','d10',56.695,-3.8737,'photo','Klassisk utsikt över Loch Tummel och bergen.','30–60 min','Sen eftermiddag','Besöksparkering'],
['Killiecrankie Gorge','Pitlochry','d10',56.744,-3.776,'hike','Skog, ravin, historia och kortare promenader.','1–2 tim','Flexibelt','National Trust-parkering'],
['Edradour Distillery','Pitlochry','d10',56.698,-3.702,'food','Klassisk destillerimiljö nära Pitlochry.','1–2 tim','Boka tur','Begränsad parkering'],
['Stirling Castle','Stirling','d11',56.1238,-3.9489,'history','Ett av Skottlands viktigaste slott med kunglig historia.','2–3 tim','Förmiddag','Parkering kan bli full'],
['Wallace Monument','Stirling','d11',56.1386,-3.9191,'history','Monument och panoramautsikt över området.','1–2 tim','Eftermiddag','Besöksparkering'],
['Curly Coo Bar','Stirling','d11',56.1185,-3.9405,'food','Liten whiskybar med stort urval och personlig atmosfär.','1–3 tim','Kväll','Parkera centralt'],
['Culross Palace','Culross','d12',56.0551,-3.6263,'history','Historisk byggnad och trädgård i välbevarad bymiljö.','1–2 tim','Förmiddag','Parkera utanför centrum'],
['Mercat Cross','Culross','d12',56.0555,-3.629,'history','Kullersten och nästan filmisk 1600-talsmiljö.','30–60 min','Förmiddag','Utforskas till fots'],
['Biscuit Café','Culross','d12',56.0558,-3.6282,'food','Cafépaus i historisk miljö.','45–75 min','Lunch','Utforskas till fots'],
['The Kelpies','Falkirk','d12',56.0192,-3.7559,'quirky','Två monumentala hästskulpturer och ett starkt avslutningsstopp.','45–90 min','Kväll','Stor besöksparkering']
].map((p,i)=>({id:`p${i+1}`,name:p[0],area:p[1],day:p[2],lat:p[3],lng:p[4],type:p[5],desc:p[6],duration:p[7],best:p[8],parking:p[9]}));
const typeMeta={all:['Alla','layout-grid'],hike:['Vandring','footprints'],beach:['Strand','waves'],history:['Historia','landmark'],nature:['Natur','trees'],photo:['Utsikt','camera'],food:['Mat & dryck','utensils'],shopping:['Service','shopping-bag'],quirky:['Unikt','sparkles'],ferry:['Färja','ship']};
const typeImages={hike:'https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1200&q=84',beach:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=84',history:'https://images.unsplash.com/photo-1577702312706-e23ff063064f?auto=format&fit=crop&w=1200&q=84',nature:'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=84',photo:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=84',food:'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=84',shopping:'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=84',quirky:'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=84',ferry:'https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=1200&q=84'};
let currentView='today',currentDay='d1',currentType='all',savedTab='favorites',map,markerLayer,routeLayer,deferredPrompt;
const favorites=new Set(JSON.parse(localStorage.getItem('scotlandFavorites')||'[]'));const visited=new Set(JSON.parse(localStorage.getItem('scotlandVisited')||'[]'));
function icon(name){return `<i data-lucide="${name}"></i>`}function refreshIcons(){if(window.lucide)lucide.createIcons()}
function persist(){localStorage.setItem('scotlandFavorites',JSON.stringify([...favorites]));localStorage.setItem('scotlandVisited',JSON.stringify([...visited]));renderCounts();renderSaved()}
function renderCounts(){document.querySelector('#placeCount').textContent=places.length;document.querySelector('#favoriteCount').textContent=favorites.size;document.querySelector('#visitedCount').textContent=visited.size;document.querySelector('#favTabCount').textContent=favorites.size;document.querySelector('#visitedTabCount').textContent=visited.size}
function initMap(){map=L.map('map',{zoomControl:true,scrollWheelZoom:false}).setView([57.18,-5.05],7);map.on('locationfound',e=>L.circleMarker(e.latlng,{radius:8,color:'#fff',weight:3,fillColor:'#1f6fe5',fillOpacity:1}).addTo(map));L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:19,subdomains:'abcd',attribution:'© OpenStreetMap © CARTO'}).addTo(map);markerLayer=L.layerGroup().addTo(map);routeLayer=L.layerGroup().addTo(map);renderMap()}
const routePoints=[[55.864,-4.252],[56.004,-4.591],[56.101,-4.641],[56.67,-5.01],[56.594,-4.93],[56.876,-5.432],[57.25,-6.256],[57.413,-6.194],[57.643,-6.265],[57.423,-6.789],[57.586,-6.358],[57.899,-6.809],[57.899,-6.951],[57.998,-7.088],[58.197,-6.745],[58.295,-6.793],[58.515,-6.261],[58.209,-6.387],[57.895,-5.161],[56.71,-3.8],[56.124,-3.949],[56.055,-3.626],[56.019,-3.756],[55.864,-4.252]];
function markerHtml(place,active=false){return `<div class="custom-marker ${active?'active':''}">${icon(typeMeta[place.type][1])}</div>`}
function renderMap(){if(!map)return;markerLayer.clearLayers();routeLayer.clearLayers();L.polyline(routePoints,{color:'#173d31',weight:5,opacity:.86,lineCap:'round',lineJoin:'round'}).addTo(routeLayer);L.polyline([[57.586,-6.358],[57.899,-6.809]],{color:'#5e87a4',weight:4,dashArray:'8 9'}).addTo(routeLayer);L.polyline([[58.209,-6.387],[57.895,-5.161]],{color:'#5e87a4',weight:4,dashArray:'8 9'}).addTo(routeLayer);const shown=places.filter(p=>currentType==='all'||p.type===currentType);shown.forEach(p=>{const m=L.marker([p.lat,p.lng],{icon:L.divIcon({html:markerHtml(p),className:'',iconSize:[38,38],iconAnchor:[19,19]})}).addTo(markerLayer);m.on('click',()=>openPlace(p.id))});document.querySelector('#visibleCount').textContent=shown.length;renderMapList(shown)}
function renderFilters(){const el=document.querySelector('#categoryFilters');el.innerHTML=Object.entries(typeMeta).map(([key,[label,ic]])=>`<button class="filter-chip ${currentType===key?'active':''}" data-type="${key}">${icon(ic)}${label}</button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>{currentType=b.dataset.type;renderFilters();renderMap()});refreshIcons()}
function renderMapList(list){document.querySelector('#mapPlaces').innerHTML=list.map(p=>`<button class="compact-card" data-place="${p.id}"><span class="type-dot">${icon(typeMeta[p.type][1])}</span><span><strong>${p.name}</strong><small>${p.area} · ${p.duration}</small></span></button>`).join('');document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>openPlace(b.dataset.place));refreshIcons()}
function renderDays(){document.querySelector('#dayRail').innerHTML=days.map((d,i)=>`<button class="day-pill ${d.id===currentDay?'active':''}" data-select-day="${d.id}"><strong>Dag ${i+1} · ${d.date}</strong><small>${d.area}</small></button>`).join('');document.querySelectorAll('[data-select-day]').forEach(b=>b.onclick=()=>selectDay(b.dataset.selectDay));renderDayContent();}
function dayPlaces(){return places.filter(p=>p.day===currentDay)}
function selectDay(id){currentDay=id;renderDays();if(currentView!=='plan')switchView('plan')}
function renderDayContent(){const day=days.find(d=>d.id===currentDay),ps=dayPlaces();const hero=document.querySelector('#dayHero');hero.style.backgroundImage=`url('${day.image}')`;hero.innerHTML=`<div class="day-hero-content"><span class="kicker">${day.date.toUpperCase()} · DAG ${days.indexOf(day)+1}</span><h2>${day.area}</h2><p>${day.route}</p><div class="day-stats"><span>${icon('car-front')}${day.drive}</span><span>${icon('clock-3')}${day.time}</span><span>${icon('bed-double')}${day.overnight}</span></div></div>`;document.querySelector('#timeline').innerHTML=ps.map((p,i)=>`<article class="timeline-item"><div class="timeline-number">${String(i+1).padStart(2,'0')}</div><div class="timeline-card"><div><h3>${p.name}</h3><p>${p.desc}</p><div class="meta"><span>${p.duration}</span><span>${p.best}</span></div></div><button data-place="${p.id}" aria-label="Öppna ${p.name}">${icon('chevron-right')}</button></div></article>`).join('')||'<div class="empty-state">Inga stopp tillagda för dagen.</div>';const mapsUrl=buildDayMapsUrl(ps);document.querySelector('#dayGuide').innerHTML=`<span class="kicker">DAGENS STRATEGI</span><h3>${day.focus}</h3><div class="guide-list"><div class="guide-row">${icon('lightbulb')}<div><strong>Rekommendation</strong><span>${day.note}</span></div></div><div class="guide-row">${icon('map-pin')}<div><strong>Övernattning</strong><span>${day.overnight}</span></div></div><div class="guide-row">${icon('list-checks')}<div><strong>Antal planerade stopp</strong><span>${ps.length} platser</span></div></div></div>${ps.length?`<a class="primary-button" href="${mapsUrl}" target="_blank" rel="noopener">${icon('navigation')} Öppna dagens rutt</a>`:''}`;document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>openPlace(b.dataset.place));refreshIcons()}
function buildDayMapsUrl(ps){if(!ps.length)return '#';const origin=`${ps[0].lat},${ps[0].lng}`,destination=`${ps.at(-1).lat},${ps.at(-1).lng}`,waypoints=ps.slice(1,-1).map(p=>`${p.lat},${p.lng}`).join('|');return `https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${destination}${waypoints?`&waypoints=${encodeURIComponent(waypoints)}`:''}&travelmode=driving`}
function openPlace(id){const p=places.find(x=>x.id===id);if(!p)return;const day=days.find(d=>d.id===p.day);document.querySelector('#sheetContent').innerHTML=`<div class="sheet-hero" style="background-image:url('${typeImages[p.type]}')"><div><span class="kicker">${p.area.toUpperCase()}</span><h2>${p.name}</h2><span>${typeMeta[p.type][0]}</span></div></div><div class="sheet-body"><p>${p.desc}</p><div class="info-grid"><div class="info-cell">${icon('clock-3')}<strong>Tidsåtgång</strong><span>${p.duration}</span></div><div class="info-cell">${icon('sun-medium')}<strong>Bästa tid</strong><span>${p.best}</span></div><div class="info-cell">${icon('caravan')}<strong>Campervan</strong><span>${p.parking}</span></div><div class="info-cell">${icon('calendar-days')}<strong>Resdag</strong><span>${day.date} · ${day.area}</span></div></div><div class="sheet-actions"><a class="navigate" href="https://www.google.com/maps/search/?api=1&query=${p.lat},${p.lng}" target="_blank" rel="noopener">${icon('navigation')} Navigera</a><button data-favorite="${p.id}">${icon(favorites.has(p.id)?'heart-off':'heart')} ${favorites.has(p.id)?'Ta bort favorit':'Spara favorit'}</button><button data-visited="${p.id}">${icon(visited.has(p.id)?'rotate-ccw':'circle-check')} ${visited.has(p.id)?'Markera obesökt':'Markera besökt'}</button></div></div>`;const sheet=document.querySelector('#placeSheet');sheet.classList.add('open');sheet.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';document.querySelector('[data-favorite]').onclick=()=>{favorites.has(p.id)?favorites.delete(p.id):favorites.add(p.id);persist();openPlace(p.id)};document.querySelector('[data-visited]').onclick=()=>{visited.has(p.id)?visited.delete(p.id):visited.add(p.id);persist();openPlace(p.id)};refreshIcons()}
function closeSheet(){const s=document.querySelector('#placeSheet');s.classList.remove('open');s.setAttribute('aria-hidden','true');document.body.style.overflow=''}
function renderSaved(){const ids=savedTab==='favorites'?favorites:visited,list=places.filter(p=>ids.has(p.id));document.querySelector('#savedPlaces').innerHTML=list.length?list.map(p=>`<button class="saved-card" data-place="${p.id}"><span class="type-dot">${icon(typeMeta[p.type][1])}</span><h3>${p.name}</h3><p>${p.area} · ${p.duration}</p></button>`).join(''):`<div class="empty-state">${savedTab==='favorites'?'Inga favoriter sparade ännu.':'Inga platser markerade som besökta ännu.'}</div>`;document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>openPlace(b.dataset.place));refreshIcons()}
function switchView(view){currentView=view;document.querySelectorAll('.section-view').forEach(s=>{const match=s.dataset.view===view;s.hidden=!match;s.classList.toggle('active',match)});document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));window.scrollTo({top:0,behavior:'smooth'});if(view==='map'){setTimeout(()=>{map.invalidateSize();renderMap()},80)}if(view==='saved')renderSaved();refreshIcons()}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav],[data-open-view]');if(nav)switchView(nav.dataset.nav||nav.dataset.openView);const day=e.target.closest('[data-day]');if(day)selectDay(day.dataset.day);if(e.target.closest('[data-close-sheet]'))closeSheet()});
document.querySelector('#fitRouteBtn').onclick=()=>map.fitBounds(L.latLngBounds(routePoints).pad(.08));document.querySelector('#resetFilters').onclick=()=>{currentType='all';renderFilters();renderMap()};document.querySelector('#locateBtn').onclick=()=>map.locate({setView:true,maxZoom:13});
document.querySelector('#themeBtn').onclick=()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'':'dark';localStorage.setItem('scotlandTheme',dark?'light':'dark');document.querySelector('#themeBtn').innerHTML=icon(dark?'moon':'sun');refreshIcons()};
document.querySelectorAll('[data-saved-tab]').forEach(b=>b.onclick=()=>{savedTab=b.dataset.savedTab;document.querySelectorAll('[data-saved-tab]').forEach(x=>x.classList.toggle('active',x===b));renderSaved()});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;const btn=document.querySelector('#installBtn');btn.hidden=false;btn.onclick=async()=>{deferredPrompt.prompt();await deferredPrompt.userChoice;btn.hidden=true;deferredPrompt=null}});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
if(localStorage.getItem('scotlandTheme')==='dark')document.documentElement.dataset.theme='dark';
renderCounts();renderFilters();renderDays();renderSaved();initMap();refreshIcons();
